### ISSUE TITLE
From scraping to registration API

### ISSUE THREAD

**Issue by bmiddha** [wilt00/finals-dashboard-ts#5]
ditch `cheerio` and its `jquery` syntax for UIC's registration API.
might be able to move everything to frontend.

**Comment by wilt00** [comment]
Honestly at that point, may as well rewrite the whole thing. Personally I've got my eye on [Elm](https://elm-lang.org/), but someone else might want React or Vue or something.

**Comment by wilt00** [comment]
And I think it's polite to proxy and cache the API out of our servers as well, to reduce the load on the university.

**Comment by bmiddha** [comment]
For this application I wouldn't want to use React or Vue, since layout is so simple. Maybe if we need something where the user signs in and adds all their courses, with a management console; that might justify the use of a front-end js framework.
